// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hilarys_Hair_Care.Migrations
{
    [DbContext(typeof(HilarysHairCareDbContext))]
    [Migration("20230921132847_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppointmentService", b =>
                {
                    b.Property<int>("AppointmentsId")
                        .HasColumnType("integer");

                    b.Property<int>("ServicesId")
                        .HasColumnType("integer");

                    b.HasKey("AppointmentsId", "ServicesId");

                    b.HasIndex("ServicesId");

                    b.ToTable("AppointmentService");

                    b.HasData(
                        new
                        {
                            AppointmentsId = 1,
                            ServicesId = 1
                        },
                        new
                        {
                            AppointmentsId = 1,
                            ServicesId = 6
                        },
                        new
                        {
                            AppointmentsId = 2,
                            ServicesId = 2
                        },
                        new
                        {
                            AppointmentsId = 2,
                            ServicesId = 3
                        });
                });

            modelBuilder.Entity("HilarysHairCare.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Paid")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("StylistId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TotalCost")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            IsActive = true,
                            ScheduledTime = new DateTime(2023, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 3,
                            IsActive = true,
                            ScheduledTime = new DateTime(2023, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        });
                });

            modelBuilder.Entity("HilarysHairCare.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Loretta",
                            LastName = "Faulker"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "John",
                            LastName = "Faulker"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Alice",
                            LastName = "Faulker"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Michael",
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Daniel",
                            LastName = "Williams"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Sophia",
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Craig",
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "James",
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Alex",
                            LastName = "Wilson"
                        });
                });

            modelBuilder.Entity("HilarysHairCare.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Basic Cut & Styling",
                            Price = 75m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hair Coloring",
                            Price = 150m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Facial Hair Removal",
                            Price = 25m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Extensions",
                            Price = 95m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Chemical Treatment",
                            Price = 60m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Hair Treatment",
                            Price = 45m
                        });
                });

            modelBuilder.Entity("HilarysHairCare.Models.Stylist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Stylists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Emily",
                            IsActive = true,
                            LastName = "Holmes"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Ava",
                            IsActive = true,
                            LastName = "Holmes"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Ben",
                            IsActive = true,
                            LastName = "Millions"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Sarah",
                            IsActive = false,
                            LastName = "Sharp"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Allie",
                            IsActive = false,
                            LastName = "Wade"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Megan",
                            IsActive = true,
                            LastName = "Bloom"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "David",
                            IsActive = true,
                            LastName = "Crips"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Jess",
                            IsActive = true,
                            LastName = "Hedge"
                        });
                });

            modelBuilder.Entity("AppointmentService", b =>
                {
                    b.HasOne("HilarysHairCare.Models.Appointment", null)
                        .WithMany()
                        .HasForeignKey("AppointmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HilarysHairCare.Models.Service", null)
                        .WithMany()
                        .HasForeignKey("ServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
